### PR TITLE
~ 0.2.2

### PR DESCRIPTION
**Pull request by seeReadCode**
@hburgund PR for the work to date on the framework.  Please let me know if you have any questions.

### CODE REVIEW

**Comment by hburgund** [comment]
I've asked @zobkiw to review this when he has a chance as it is building off of his work and he has a good idea of where things are going in the future as well.

So we'll see what he has to say and also, I will likely want this merged into `develop` not `master`, but I'll let you know, so don't bother changing anything yet.

**Comment by zobkiw** [comment]
Upon launching the workspace I was immediately prompted to update to Swift 3.0.

**Comment by sinabahram** [comment]
Correct. My understanding is that this has been updated to 3.0.

**Comment by zobkiw** [comment]
If it was updated to Swift 3.0 then I shouldn't be prompted to update syntax then, correct?

**Comment by seeReadCode** [comment]
@zobkiw I'll try cloning to a new directory to see if I can replicate and resolve.  But yes, the swift 3.0 conversion should be complete.

**Comment by zobkiw** [comment]
Basically I pulled it fresh, pod update, open workspace. That's about it.

screenshot 2017-03-07 17 20 07

If there are any pods here that are not necessary I would suggest removing them as well. Nothing worse (IMO) than a pod that depends on other pods. :-)

**Comment by sinabahram** [comment]
Understood. Thanks for pointing this out.

**Comment by seeReadCode** [comment]
@zobkiw I'm not getting this message when I clone the framework from my repo/branch into a new directory, pod install and open. You might check that your coffeepods is up to date.  

`bundle install` might do the trick for you in the  `Example` directory.  I removed the pods that were referenced in the test block since those were the only unused ones (we are using SwiftyJson).  Please let me know where that gets you.

**Comment by seeReadCode** [comment]
re: swift 3 https://github.com/seeRead/roundware-ios-framework-v2/issues/6

**Comment by seeReadCode** [comment]
Also, it should go without saying but thanks for looking this over :)

**Comment by zobkiw** [comment]
Much better - builds now - thanks. 

* The example has 4 warnings that should be cleaned up
* RWFramework project has some project settings that Xcode wants to update
* Linker warning for tests, most likely an entry in build settings
* The example doesn't actually point to a test project - might be worth doing that so it can be used out of the box

**Comment by seeReadCode** [comment]
Buildtime warnings have been cleared (and issues have been transferred).  @hburgund your call on the test project item.

**Pull request closed without merging**
